### ISSUE TITLE
GWT transpiler problem

### ISSUE THREAD

**Issue by CommonGrounds** [webfx-project/webfx-cli#13]
After recent changes ( 4 hours before )  gwt transpiler show error :+1: 
`[ERROR] Line 31: dev.webfx.platform.boot.spi.impl.ApplicationJobsBooter cannot be resolved to a type`
Before this changes everything was fine.

**Comment by salmonb** [comment]
I may have pushed some breaking changes this afternoon, but a `webfx update` on your project should make you back on track. Let me know if not.

**Comment by salmonb** [comment]
If `webfx update` doesn't work, try `webfx update -c` to make sure you have fresh Maven snapshots (including webfx.xml files from WebFX libraries such as WebFX Platform).

**Comment by CommonGrounds** [comment]
Now even webfx update -c doesnt help :

`[ERROR] Failed to execute goal on project Meteo_WebFX-application: Could not resolve dependencies for project com.java4now:Meteo_WebFX-application:jar:1.0.0-SNAPSHOT: The following artifacts could not be resolved: org.openjfx:javafx-controls:jar:${javafx.platform}:19 (absent), org.openjfx:javafx-graphics:jar:${javafx.platform}:19 (absent), org.openjfx:javafx-base:jar:${javafx.platform}:19 (absent), org.openjfx:javafx-media:jar:${javafx.platform}:19 (absent): org.openjfx:javafx-controls:jar:${javafx.platform}:19 was not found in https://nexus.gluonhq.com/nexus/content/repositories/releases during a previous attempt. This failure was cached in the local repository and resolution is not reattempted until the update interval of gluon-repository has elapsed or updates are forced -> [Help 1]
`

**Comment by salmonb** [comment]
That's a complete separate issue that is actually related to JavaFX and not WebFX.

See https://stackoverflow.com/questions/78542808/maven-project-fails-to-resolve-javafx-dependencies

The JavaFX Maven artifacts have an issue since a long time ago, which was tolerated by previous Maven version but not recent ones (> 3.9.6). Have you upgraded your Maven version?

The solution for now is to downgrade Maven to a compatible version with JavaFX, until the JavaFX team fixes that problem.

**Comment by salmonb** [comment]
José Pereda said in a recent comment on the stackoverflow page that the issue with the JavaFX pom has been fixed with JavaFX 23-ea+20.

So try to include this in your `webfx.xml` located at your project root level:
```xml
    <maven-pom-manual>
        <properties>
            <openjfx.version>23-ea+20</openjfx.version>
        </properties>
    </maven-pom-manual>
```
and then `webfx update`. This should bump your project to OpenJFX 23-ea+20.

Let me know if this solves the issue.

**Comment by CommonGrounds** [comment]
thanks for the amazingly fast reply!
Yes, I upgrade  maven version, i try your suggestion and report back. Thanks;

**Comment by salmonb** [comment]
You're welcome!

If you need support for your meteo app, feel free to ask questions on the [WebFX Discord chat](https://discord.gg/xJcvmGvqh9).

If you want to request a forecast web service for ex, I can explain you how to do that with the WebFX API.
